sudo: required

services:
  - docker

before_install:
  - docker build -t dwivedig/react-with-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true dwivedig/react-with-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "region-in-url"
  app: "appNameInAWS"
  env: "AWSENVName"
  bucket_name: "AWS-S3-bucker-name"
  bucker_path: "appNameInAWS"
  on:
   branch: master